spring:
  server:
    port: 80
    address: 0.0.0.0
  application:
    name: JsonPlaceholder
  datasource:
    url: jdbc:postgresql://localhost:32768/postgres
    username: postgres
    password: postgrespw

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgreSQLDialect

